### ISSUE TITLE
Issue with ConvertProperty

### ISSUE THREAD

**Issue by DMGT4** [gigaHours/Gibbed.MadMax#2]
Once again, this seems specific to certain .blo files.
This time, files in question are player vehicle configs found in "locations\a00\vehicles\s00#" where # are bodywork IDs 1, 2, 3, 4 and 7.

For example, converting "a00_vh_s002_location.xml" [Shovelface bodywork] and copying it into [install dir]\dropzone\locations\a00\vehicles\s002 will crash the game the second it needs to load a player car with this bodywork installed.
If a different bodywork is installed, and then Shovelface is previewed, game will only render the car's wheels. Installing this bodywork and exiting the Garage menu will crash the game.

Dropzone can be enabled with the following launch options:
-vfs-fs dropzone -vfs-archive patch_win64 -vfs-archive archives_win64 -vfs-archive dlc_win64 -vfs-fs .
Remove "-vfs-archive dlc_win64" if dlc is not installed.

**Comment by gigaHours** [comment]
Fixed in 1.2 Version
